### ISSUE TITLE
Only compiling under windows (I assume)

### ISSUE THREAD

**Issue by tskardal** [LWJGL/lwjgl3-demos#1]
I tried buidling on a linux machine and I end up with errors in SwtHelperWin32 no matter what I do. I've tried specifying the linux maven profiles.

To me it seems like this is caused by 33bd2b141cfb2156aa04f988a9e27d6b40ffd950

Error
```
lwjgl3-demos/src/org/lwjgl/demo/opengl/swt/SwtHelperWin32.java:[10,57] cannot find symbol
[ERROR] symbol:   variable OS
[ERROR] location: class org.lwjgl.demo.opengl.swt.SwtHelperWin32

```

**Comment by httpdigest** [comment]
Sorry. That was a leftover from some Win32 API experiments that unfortunately made it into the demos repository.
Fixed.

**Comment by tskardal** [comment]
That was fast! Builds now. :smiley:

**Comment by httpdigest** [comment]
Glad it works now! :)

> I've tried specifying the linux maven profiles.

You should be able to build with Maven (on the command-line or on a Maven-capable IDE) without specifying a profile. The platform will be auto-detected by Maven and the appropriate platform-dependent LWJGL3 and SWT libraries used.
